// Generated by CoffeeScript 1.12.7
(function() {
  var i, j, k, l, len, sum, time, x;

  x = [
    3, 5, 'Dojo', 'rocks', {
      name: 'Michael',
      title: 'Sensei'
    }
  ];

  for (j = 0, len = x.length; j < len; j++) {
    i = x[j];
    console.log(i + ": " + (typeof i));
  }

  x.push(100);

  x.push([]);

  console.log(x);

  sum = 0;

  for (i = k = 1; k <= 500; i = ++k) {
    sum += i;
  }

  console.log(sum);

  time = Date.now();

  sum = 0;

  for (i = l = 1; l <= 1000000; i = ++l) {
    sum += i;
  }

  time = Date.now() - time;

  console.log(sum, time);

}).call(this);
